export default {
    ts: "TypeScript",
    js: "JavaScript",
    python: "Python",
    sqlite: "SQLite",
    mongo: "MongoDB",
    postgreSql: "PostgreSQL",
    html: "HTML",
    css: "CSS",
    sass: "SASS",
    scss: "SCSS",
    less: "Less",
    stylus: "Stylus",
    ejs: "EJS",
    jinja: "Jinja2",
    node: "Node.js",
    vscode: "VSCode",
    nvim: "NeoVim",
    figma: "Figma",
    git: "Git & GitHub",
    xfce: "XFCE",
    react: "React",
    discordJs: "Discord.js",
    flask: "Flask",
    quart: "Quart",
    express: "Express",
    rtk: "RTK",
    zod: "Zod",
    webpack: "WebPack",
    pug: "Pug",
    gulp: "Gulp",
    next: "Next",
    deno: "Deno",
    pixijs: "PixiJS",
    preact: "Preact",
    
    // Cybersecurity related terms
    appsec: "Application Security",
    web: "Web Security",
    security: "Security",
    pentesting: "Penetration Testing",
    hacking: "Ethical Hacking",
    owasp: "OWASP",
    websec: "Web Security",
    vulnerabilities: "Vulnerabilities",
    ctf: "CTF",
    writeup: "Writeups",
    challenge: "Security Challenges",
    api: "API Security",
    rest: "REST Security",
    threat: "Threat Modeling",
    intelligence: "Intelligence",
    cloud: "Cloud Security",
    aws: "AWS Security",
    docker: "Docker Security",
    kubernetes: "Kubernetes",
    devsecops: "DevSecOps",
    automation: "Security Automation",
    devops: "DevOps",
    coding: "Secure Coding",
    development: "Secure Development",
    cicd: "CI/CD Security",
    mobile: "Mobile Security",
    android: "Android Security",
    malware: "Malware Analysis",
    analysis: "Security Analysis"
}